services:
  qdrant:
    image: qdrant/qdrant:v1.15.5
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__STORAGE__USE_MMAP=false
      - QDRANT__STORAGE__ON_DISK_PERSISTENCE=true
    volumes:
      # Use repo-relative storage directory (infra/.. -> data)
      - ../data/qdrant:/qdrant/storage
  redis:
    image: redis/redis-stack:7.2.0-v10
    container_name: rag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      # Dev mode: no persistence (prevents AOF corruption on crash)
      - REDIS_ARGS=--save ""
    # No volumes needed without persistence
    # volumes:
    #   - ../data/redis:/data
